<a href="https://colab.research.google.com/github/JuneshG/Generative-AI/blob/main/Attention_Mechanism_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import array
from numpy import random
from numpy import dot
from scipy.special import softmax

# encoder representations of four different friends
friend_1 = array([1, 0, 0])  # Speed enthusiast
friend_2 = array([0, 1, 0])  # Comfort lover
friend_3 = array([1, 1, 0])  # Balanced speed and comfort
friend_4 = array([0, 0, 1])  # Tech-savvy

# stacking the friend preferences into a single array
friends = array([friend_1, friend_2, friend_3, friend_4])

# generating the weight matrices
random.seed(42)
W_Q = random.randint(3, size=(3, 3))  # Urgency matrix
W_K = random.randint(3, size=(3, 3))  # Cost matrix
W_V = random.randint(3, size=(3, 3))  # Feature matrix

# generating the queries, keys and values
Q = friends @ W_Q  # How urgently each friend wants features
K = friends @ W_K  # Cost considerations for each preference
V = friends @ W_V  # Features of each motorcycle

# scoring the query vectors against all key vectors
scores = Q @ K.transpose()  # Matching urgency with cost

# computing the weights by a softmax operation
weights = softmax(scores / K.shape[1] ** 0.5, axis=1)  # Balancing urgency and cost

# computing the attention by a weighted sum of the value vectors
attention = weights @ V  # Optimal feature set for each friend

print(attention)

[[0.98522025 1.74174051 0.75652026]
 [0.90965265 1.40965265 0.5       ]
 [0.99851226 1.75849334 0.75998108]
 [0.99560386 1.90407309 0.90846923]]


#Motorcycle Buying Scenario
##Friends and Preferences:
Friend 1 (Speed Enthusiast): Loves fast motorcycles.\
Friend 2 (Comfort Lover): Prioritizes comfort and smooth rides.\
Friend 3 (Balanced): Wants a mix of speed and comfort.\
Friend 4 (Tech-Savvy): Interested in advanced technology features.


##Weight Matrices:
W_Q (Urgency Matrix): How urgently each friend wants specific features.
W_K (Cost Matrix): Cost considerations for each type of motorcycle.
W_V (Feature Matrix): The features available in different motorcycles.

##Generating Queries, Keys, and Values:
Q (Queries): Represents how urgently each friend desires certain features.\
K (Keys): Represents cost considerations for those features.\
V (Values): Represents the feature set available in different motorcycles.

##Scoring and Weighting:
The code calculates how well each friend's urgency matches with cost constraints.\
Softmax ensures a balanced consideration of urgency and cost.

##Computing Attention:

The final attention output represents the optimal feature set for each friend's preferred motorcycle.\
Each row in 'attention' shows how well each motorcycle aligns with their
preferences.

##Interpreting the Output
The output will be a matrix where each row corresponds to one friend's optimal motorcycle choice based on their preferences:

Friend 1: Likely to choose a motorcycle with high speed features.\
Friend 2: Will prioritize comfort-related features.\
Friend 3: Will look for a balance between speed and comfort.\
Friend 4: Will focus on motorcycles with advanced tech features.

This output helps each friend understand which motorcycle best suits their needs while considering both their urgency for certain features and the associated costs. 🏍️