<a href="https://colab.research.google.com/github/JuneshG/Generative-AI/blob/main/Attention_Mechanism_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import array
from numpy import random
from numpy import dot
from scipy.special import softmax

# encoder representations of four different friends
friend_1 = array([1, 0, 0])  # Speed enthusiast
friend_2 = array([0, 1, 0])  # Comfort lover
friend_3 = array([1, 1, 0])  # Balanced speed and comfort
friend_4 = array([0, 0, 1])  # Tech-savvy

# stacking the friend preferences into a single array
friends = array([friend_1, friend_2, friend_3, friend_4])

# generating the weight matrices
random.seed(42)
W_Q = random.randint(3, size=(3, 3))  # Urgency matrix
W_K = random.randint(3, size=(3, 3))  # Cost matrix
W_V = random.randint(3, size=(3, 3))  # Feature matrix

# generating the queries, keys and values
Q = friends @ W_Q  # How urgently each friend wants features
K = friends @ W_K  # Cost considerations for each preference
V = friends @ W_V  # Features of each motorcycle

# scoring the query vectors against all key vectors
scores = Q @ K.transpose()  # Matching urgency with cost

# computing the weights by a softmax operation
weights = softmax(scores / K.shape[1] ** 0.5, axis=1)  # Balancing urgency and cost

# computing the attention by a weighted sum of the value vectors
attention = weights @ V  # Optimal feature set for each friend

print(attention)

[[0.98522025 1.74174051 0.75652026]
 [0.90965265 1.40965265 0.5       ]
 [0.99851226 1.75849334 0.75998108]
 [0.99560386 1.90407309 0.90846923]]
